#!/usr/bin/env python

## \namespace multiphonon::applications::wxGetDOS
##
## This application is a GUI interface for extracting DOS from S(Q,E)
##
## The GUI interface is mostly automatically generated by pyregui package.
## But the GUI toolkit for pyregui has been overloaded to achieve better user experience.
##
## The pyregui package is still a prototype. So this application will evolve as
## pyregui moves to better and more stable design.
##


from pyregui.pyreui import run


import journal
journal.error( "pyre.inventory" ).deactivate()


def main():
    appfilename = "GetDOS.py"
    classname = "GetdosApp"
    #from multiphonon.applications.gui import wx
    from pyregui.guitoolkit import wx
    run( appfilename, classname, wx )
    return



if __name__ == "__main__": main()

